
import { GoogleGenAI, Modality } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable is not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const fileToGenerativePart = (base64: string, mimeType: string) => {
  return {
    inlineData: {
      data: base64,
      mimeType,
    },
  };
};

export const generateLineArt = async (
  imageBase64: string,
  mimeType: string
): Promise<string> => {
  try {
    const imagePart = fileToGenerativePart(imageBase64, mimeType);
    const prompt = `Convert this image into a clean, black and white line art coloring page. The lines should be distinct and clear, suitable for coloring. Remove all shading, color, and complex textures, leaving only the essential outlines. The background should be pure white.`;
    
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          { text: prompt },
          imagePart
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    const firstPart = response.candidates?.[0]?.content?.parts?.[0];
    if (firstPart && firstPart.inlineData) {
      return firstPart.inlineData.data;
    } else {
      throw new Error("No line art image was generated by the API.");
    }
  } catch (error) {
    console.error("Error generating line art:", error);
    throw new Error("Failed to generate line art. Please check the console for details.");
  }
};
